site_name: Introduction to Materials Science
site_url: https://intromatsci.com/
nav:
    - Home: index.md
    - Syllabus: syllabus.md
    - 'Module 1 - Real Space':
        - 'Lesson 1: Atoms':             'Module 1/1 Atoms.md'
        - 'Lesson 2: Crystal structure': 'Module 1/2-structure.md'
        - 'Lesson 3: More':              'Module 1/3-structure.md'
    - 'Module 2 - Reciprocal Space':
        - '1) Intro':             'Module 2/1-intro.md'
        - '2) Crystal structure': 'Module 2/2-structure.md'
    - 'Module 3 - Electronic Structure':
        - '1) Intro':             'Module 3/1-intro.md'
        - '2) Crystal structure': 'Module 3/2-structure.md'

theme:
  name: material
  language: en
   
  icon:
    repo: fontawesome/brands/github
  
  # Coloring for light/dark themes
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: teal
      accent: teal

  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - content.code.annotate

# Adding versioning tags to the website
# extra:
#   version:
#     provider: mike
#     default: stable
# !!! https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

# For emojis, annotations, etc.
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true


# For search bar and automatic generation of api docs
plugins:
    - glightbox
#    - search
#    - mkdocstrings:
#        default_handler: python
